### ISSUE TITLE
Make positions more visible to users + possibly alter team member design

### ISSUE THREAD

**Issue by thelbaumann** [mdurst365/Project2#21]
Need to create a "drag area" for the user to see that is still responsive enough on desktop. May require using position names absolutely or not. Team Member symbols could use more styling if there is time.

**Comment by mdurst365** [comment]
I played around with using CSS hover to do this, but could not come up with a solution that looked good - it might be a good step in finding the right fix though.

https://developer.mozilla.org/en-US/docs/Web/CSS/:hover

**Comment by thelbaumann** [comment]
Left dashed circles where positions reside and added team numbers to players on the field!

**Comment by mdurst365** [comment]
looks great!
